name: gradebook
packages:
  - apps/client_flutter
  - packages/api_client_dart
scripts:
  check:
    run: dart run melos exec --scope=client_flutter --concurrency=1 -- "dart format --output=none --set-exit-if-changed lib test && flutter analyze && flutter test"
  dev:web:
    run: dart run melos exec --scope=client_flutter --concurrency=1 -- "flutter run -d chrome --web-port=8080 --dart-define-from-file=config/development.json"
